app: sp
service: smart-parking
provider:
    name: aws
    runtime: nodejs12.x
    profile: smart-parking
    memorySize: 128
    versionFunctions: false
    region: us-east-1
    iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:Query
          Resource:
              - '*'
        - Effect: Allow
          Action: dynamodb:Scan
          Resource:
              - '*'
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource:
              - '*'

plugins:
    - serverless-appsync-plugin
    - serverless-jetpack

package:
    individually: true
    include:
        - '!*'
        - '!*/**'

functions:
    - ${file(functions/serverless.yml)}

custom:
    stage: ${opt:stage, self:provider.stage}
    appSyncApiKey:
        dev: 'da2-rhdii5t3wndspjice67hw2qpoq'
        prod: 'da2-2gmou56ouveq3nsmdalp2pgoxe'
    output:
        file: ../frontend/src/stack.json
    appSync:
        name: ${self:app}-api-${self:custom.stage}
        schema: ../frontend/schema.graphql
        authenticationType: API_KEY
        mappingTemplates:
            - ${file(mapping-templates/fields.yml)}
        dataSources:
            - ${file(data-sources.yml)}
    jetpack:
        concurrency: 3

resources:
    - Conditions:
          isProd: !Equals ['${self:custom.stage}', prod]

    - ${file(resources/dynamodb.yml)}
    - ${file(resources/outputs.yml)}
